[tool.poetry]
name = "evremixes"
version = "2.1.0"
description = "Evanescence Remix Downloader"
authors = ["Danny Stewart <danny@stewart.cc>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
halo = "^0.0.31"
inquirer = "^3.1.3"
mutagen = "^1.47.0"
pillow = "^10.1.0"
requests = "^2.31.0"
termcolor = "^2.3.0"
types-requests = "^2.31.0.20240406"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^6.4.0"
pylint = "^3.0.2"
ruff = "^0.1.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100

[tool.flake8]
max-line-length = 100

[tool.ruff]
line-length = 100
exclude = [
    ".git",
    ".pyenv",
    ".venv",
    ".vscode",
    "__pypackages__",
    "build",
    "dist",
    "venv",
]
