[tool.poetry]
name = "evremixes"
version = "1.0.0"
description = "Evanescence Remix Downloader"
authors = ["Danny Stewart <danny@stewart.cc>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
azure-storage-blob = "^12.18.3"
halo = "^0.0.31"
inquirer = "^3.1.3"
mutagen = "^1.47.0"
pillow = "^10.1.0"
pydub = "^0.25.1"
pyperclip = "^1.8.2"
python-dotenv = "^1.0.0"
requests = "^2.31.0"
telebot = "^0.0.5"
termcolor = "^2.3.0"

[tool.poetry.group.dev.dependencies]
ufmt = "^2.3.0"
black = "^23.10.1"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 110
