[tool.poetry]
name = "evremixes"
version = "3.0.0"
description = "Evanescence Remix Downloader"
authors = ["Danny Stewart <danny@stewart.cc>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
halo = "^0.0.31"
inquirer = "3.2.5"
mutagen = "^1.47.0"
pillow = "^10.3.0"
readchar = "4.0.5"
requests = "^2.32.3"
termcolor = "^2.4.0"
types-requests = "^2.32.0.20240602"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^6.8.0"
ruff = "^0.4.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100

[tool.flake8]
max-line-length = 100

[tool.ruff]
line-length = 100
exclude = [
    ".git",
    ".pyenv",
    ".venv",
    ".vscode",
    "__pypackages__",
    "build",
    "dist",
    "venv",
]
