[tool.poetry]
name = "evremixes"
version = "3.0.0"
description = "Evanescence Remix Downloader"
authors = ["Danny Stewart <danny@stewart.cc>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
halo = "^0.0.31"
inquirer = "3.2.5"
mutagen = "^1.47.0"
pillow = "^10.4.0"
requests = "^2.32.3"
termcolor = "^2.5.0"
types-requests = "^2.32.0.20241016"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^6.11.0"
ruff = "^0.7.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
