[tool.poetry]
name = "evremixes"
version = "2.0.0"
description = "Evanescence Remix Downloader"
authors = ["Danny Stewart <danny@stewart.cc>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
halo = "^0.0.31"
inquirer = "^3.1.3"
mutagen = "^1.47.0"
pillow = "^10.1.0"
pyperclip = "^1.8.2"
python-dotenv = "^1.0.0"
requests = "^2.31.0"
termcolor = "^2.3.0"

[tool.poetry.group.dev.dependencies]
autoflake = "^2.2.1"
black = "^23.10.1"
isort = "^5.12.0"
pyinstaller = "^6.4.0"
pylama = "^8.4.1"
pylint = "^3.0.2"
pyproject-flake8 = "^6.1.0"
pytest = "^7.4.3"
pytest-timeout = "^2.2.0"
ruff = "^0.1.8"
shed = "^2023.6.1"
ssort = "^0.11.6"
yapf = "^0.40.2"

[tool.poetry.group.azure.dependencies]
azure-storage-blob = "^12.18.3"

[tool.poetry.group.telegram.dependencies]
telebot = "^0.0.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100

[tool.flake8]
max-line-length = 100

[tool.ruff]
line-length = 100
exclude = [
    ".git",
    ".pyenv",
    ".venv",
    ".vscode",
    "__pypackages__",
    "build",
    "dist",
    "venv",
]
